# Generated by Django 5.1.6 on 2025-02-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('duration', models.DurationField()),
                ('video_url', models.URLField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('main_cast', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('average_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
