# Generated by Django 5.1.6 on 2025-02-10 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_is_admin_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
