# Generated by Django 5.1.6 on 2025-02-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
