# Generated by Django 5.1.6 on 2025-03-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_movie_background_movie_director_movie_imdb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
    ]
