# Generated by Django 5.1.6 on 2025-03-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_movie_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(blank=True, null=True),
        ),
    ]
